# Generated by Django 5.1.2 on 2024-10-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_application_date', models.DateField(verbose_name='Application Date')),
                ('job_title', models.CharField(max_length=100, verbose_name='Roll')),
                ('job_type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Job')], max_length=10, verbose_name='Job Type')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('applied_link', models.URLField(verbose_name='Application Link')),
                ('job_posted_date', models.DateField(verbose_name='Job Posted Date')),
                ('job_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10, verbose_name='Status')),
            ],
        ),
    ]
