# Generated by Django 5.1.2 on 2024-10-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proTrack_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_title',
            field=models.CharField(max_length=100, verbose_name='Role'),
        ),
    ]
