# Generated by Django 5.1.2 on 2024-10-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proTrack_main', '0005_rejectedjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Job', 'Job')], max_length=10, verbose_name='Job Type'),
        ),
    ]
