# Generated by Django 5.1.2 on 2024-10-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proTrack_main', '0006_alter_jobs_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_posted_date',
            field=models.DateField(null=True, verbose_name='Job Posted Date'),
        ),
    ]
