# Generated by Django 5.1.2 on 2024-10-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proTrack_main', '0007_alter_jobs_job_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_posted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Job Posted Date'),
        ),
    ]
